# Generated by Django 4.2.30 on 2026-06-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='embeddings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
