# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_learning', '0002_note_embeddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='status',
            field=models.CharField(
                choices=[
                    ('locked', 'Locked'),
                    ('unlocked', 'Unlocked'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                ],
                default='locked',
                max_length=20,
            ),
        ),
    ]
